# Generated by Django 2.1 on 2018-11-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=500, upload_to='', width_field=500)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_address', models.CharField(max_length=200)),
                ('store_description', models.CharField(max_length=400)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.City')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.Store'),
        ),
    ]
